### ISSUE TITLE
Traducción para opción de "Share"

### ISSUE THREAD

**Issue by gabrfer** [mugan86/currency-android-kotlin#4]
Aupa, 

He estado probando hace un rato así por encima y no he visto nada mal. Lo que te pongo aquí es porque no sé si hay que traducirlo o no. En el menú contextual que sale al tocar la parte derecha del Toolbar, te da la opción de compartir la aplicación, el texto que aparece es "Share", tengas el idioma que tengas. Pero esta opción no sé si se suele traducir, porque el término "Share" es algo casi universal, como "Play", "Download", etc...

Por eso pregunto, no sé si esto se suele traducir. Borra la issue si ves que no lo es.

Un saludo.

**Comment by mugan86** [comment]
Lo dejé queriendo así, por la razón que tu comentas. Queda mejor para mi gusto aunque igual ponerlo por idioma? No se, a esto le tengo que dar vueltas. Muchas gracias! Lo dejo abierto mientras lo pienso.

Si es una pregunta, añádele el label de "question", para que quede más ordenado ;)

**Comment by gabrfer** [comment]
Ok, en realidad queria hacer eso, hacer una cuestión. No sabía lo de los labels, no estoy acostumbrado a trabajar con esto. Ahora ya lo sé jejeje.

Un saludo.

**Comment by mugan86** [comment]
Después de darle vueltas y ver un poco lo que hace la gente, he decidido dejarlo con "Share", se entiende perfecto aunque no cierro a que pueda cambiar en el futuro pero de primeras lo dejo tal cual, muchas gracias por la observación! ;)
